# https://developers.google.com/web/updates/2017/06/headless-karma-mocha-chai
language: node_js
node_js:
  - "7"
dist: trusty
sudo: required
addons:
  chrome: stable
cache:
  yarn: true
  directories:
    - node_modules
install:
  - yarn
script:
  - yarn test
